import assert from "node:assert/strict";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { gzipSync } from "node:zlib";

import { parseNpmTarball } from "./npm-release-tarball.mjs";
import { stageReleasePackages } from "./stage-release-packages.mjs";

function makeRoot() {
  const root = mkdtempSync(join(tmpdir(), "paperclip-release-stage-test-"));
  const stageRoot = join(root, "paperclip-release-stage.fixture");
  mkdirSync(stageRoot);
  writeFileSync(join(stageRoot, ".paperclip-release-stage"), "");
  return { root, stageRoot };
}

function removeFixture(root) {
  function makeWritable(path) {
    if (!existsSync(path)) return;
    const stat = statSync(path);
    chmodSync(path, stat.isDirectory() ? 0o755 : 0o644);
    if (stat.isDirectory()) {
      for (const entry of readdirSync(path)) makeWritable(join(path, entry));
    }
  }
  makeWritable(root);
  rmSync(root, { recursive: true, force: true });
}

function makeLifecyclePackage(root, dir, name, { generated = "safe generated bytes\n" } = {}) {
  const packageDir = join(root, dir);
  mkdirSync(packageDir, { recursive: true });
  const manifest = {
    name,
    version: "1.2.3",
    files: ["generated.js"],
    scripts: { prepack: "node prepack.cjs", postpack: "node postpack.cjs" },
  };
  writeFileSync(join(packageDir, "package.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(
    join(packageDir, "prepack.cjs"),
    `const fs=require("node:fs");const p=JSON.parse(fs.readFileSync("package.json"));fs.copyFileSync("package.json","package.source.json");p.packedByLifecycle=true;fs.writeFileSync("package.json",JSON.stringify(p,null,2)+"\\n");fs.writeFileSync("generated.js",${JSON.stringify(generated)});\n`,
  );
  writeFileSync(
    join(packageDir, "postpack.cjs"),
    'const fs=require("node:fs");fs.renameSync("package.source.json","package.json");\n',
  );
  return { dir, name, version: "1.2.3" };
}

test("real lifecycle scripts produce the exact scanned immutable tarball while restoring sources", () => {
  const fixture = makeRoot();
  try {
    const pkg = makeLifecyclePackage(fixture.root, "pkg-a", "@paperclipai/stage-a");
    const [staged] = stageReleasePackages({
      root: fixture.root,
      stageRoot: fixture.stageRoot,
      packages: [pkg],
      tokens: ["account_fixture_that_is_absent"],
    });

    assert.equal(statSync(staged.tarballPath).mode & 0o222, 0);
    assert.match(staged.tarballPath, new RegExp(`${staged.sha256}\\.tgz$`));
    const entries = parseNpmTarball(readFileSync(staged.tarballPath));
    const manifest = JSON.parse(
      entries.find((entry) => entry.path === "package/package.json").content.toString("utf8"),
    );
    assert.equal(manifest.packedByLifecycle, true);
    assert.equal(
      entries.find((entry) => entry.path === "package/generated.js").content.toString("utf8"),
      "safe generated bytes\n",
    );
    assert.equal(JSON.parse(readFileSync(join(fixture.root, "pkg-a/package.json"))).packedByLifecycle, undefined);
    assert.equal(existsSync(join(fixture.root, "pkg-a/package.source.json")), false);
    assert.throws(
      () =>
        parseNpmTarball(
          Buffer.concat([
            readFileSync(staged.tarballPath),
            gzipSync(Buffer.from("appended unscanned payload")),
          ]),
        ),
      /nonzero data follows the tar end marker/,
    );
  } finally {
    removeFixture(fixture.root);
  }
});

test("staging rejects a symlink masquerading as its package tarball", () => {
  const fixture = makeRoot();
  try {
    const pkg = makeLifecyclePackage(fixture.root, "pkg-a", "@paperclipai/stage-a");
    const target = join(fixture.root, "outside.tgz");
    writeFileSync(target, "not a tarball");
    assert.throws(
      () =>
        stageReleasePackages({
          root: fixture.root,
          stageRoot: fixture.stageRoot,
          packages: [pkg],
          tokens: ["account_fixture_that_is_absent"],
          runPack: (_packageDir, destination) => {
            symlinkSync(target, join(destination, "package.tgz"));
            return { status: 0, stdout: "", stderr: "" };
          },
        }),
      /exactly one regular tarball/,
    );
  } finally {
    removeFixture(fixture.root);
  }
});

test("lifecycle-generated forbidden content blocks staging without exposing it", () => {
  const fixture = makeRoot();
  try {
    const pkg = makeLifecyclePackage(fixture.root, "pkg-a", "@paperclipai/stage-a", {
      generated: 'export const leaked = "/home/runner/private";\n',
    });
    assert.throws(
      () =>
        stageReleasePackages({
          root: fixture.root,
          stageRoot: fixture.stageRoot,
          packages: [pkg],
          tokens: ["/home/runner/"],
        }),
      (error) => {
        assert.match(error.message, /forbidden token found/);
        assert.doesNotMatch(error.message, /runner|private/);
        return true;
      },
    );
  } finally {
    removeFixture(fixture.root);
  }
});

test("package order is preserved and each package receives a unique tarball", () => {
  const fixture = makeRoot();
  try {
    const packages = [
      makeLifecyclePackage(fixture.root, "pkg-b", "@paperclipai/stage-b"),
      makeLifecyclePackage(fixture.root, "pkg-a", "@paperclipai/stage-a"),
    ];
    const staged = stageReleasePackages({
      root: fixture.root,
      stageRoot: fixture.stageRoot,
      packages,
      tokens: ["account_fixture_that_is_absent"],
    });
    assert.deepEqual(staged.map((entry) => entry.name), packages.map((entry) => entry.name));
    assert.equal(new Set(staged.map((entry) => entry.tarballPath)).size, 2);
    assert.match(staged[0].tarballPath, /\/001\/001-[a-f0-9]{64}\.tgz$/);
    assert.match(staged[1].tarballPath, /\/002\/002-[a-f0-9]{64}\.tgz$/);
  } finally {
    removeFixture(fixture.root);
  }
});

test("release staging cannot silently proceed with an empty token policy", () => {
  const fixture = makeRoot();
  try {
    const pkg = makeLifecyclePackage(fixture.root, "pkg-a", "@paperclipai/stage-a");
    assert.throws(
      () => stageReleasePackages({ root: fixture.root, stageRoot: fixture.stageRoot, packages: [pkg], tokens: [] }),
      /policy is empty/,
    );
  } finally {
    removeFixture(fixture.root);
  }
});
